env:
  browser: true
  es2021: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  project: tsconfig.json
  sourceType: module
plugins:
  - react
  - simple-import-sort
  - import
  - '@typescript-eslint'
rules:
  simple-import-sort/imports: error
  simple-import-sort/exports: error
  import/first: error
  import/newline-after-import: error
  import/no-duplicates: error
  react/react-in-jsx-scope: off
settings:
  react:
    version: detect
